### ISSUE TITLE
Add Improvers for the migrated importers

### ISSUE THREAD

**Issue by TG1999** [nexB/vulnerablecode#1034]
- [x] Apache HTTPD ( PR under progress #1102 )
- [x] NPM ( PR under progress #1138  )
- [x] Istio ( PR under progress #1103 )
- [x] Elixir_security ( PR under progress #1138  )
- [x] Apache Kafka (PR under progress #1138 )
- [x] Apache Tomcat ( PR under progress #1138  )

**Comment by TG1999** [comment]
Done in #1138
